var _states = [
	{ name: 'Alabama', abbr: 'AL', x: 7, y: 6 },
	{ name: 'Alaska', abbr: 'AK', x: 0, y: 0 },
	{ name: 'Arizona', abbr: 'AZ', x: 2, y: 5 },
	{ name: 'Arkansas', abbr: 'AR', x: 5, y: 5 },
	{ name: 'California', abbr: 'CA', x: 1, y: 4 },
	{ name: 'Colorado', abbr: 'CO', x: 3, y: 4 },
	{ name: 'Connecticut', abbr: 'CT', x: 10, y: 3 },
	{ name: 'Delaware', abbr: 'DE', x: 10, y: 4 },
	{ name: 'Florida', abbr: 'FL', x: 9, y: 7 },
	{ name: 'Georgia', abbr: 'GA', x: 8, y: 6 },
	{ name: 'Hawaii', abbr: 'HI', x: 0, y: 7 },
	{ name: 'Idaho', abbr: 'ID', x: 2, y: 2 },
	{ name: 'Illinois', abbr: 'IL', x: 6, y: 2 },
	{ name: 'Indiana', abbr: 'IN', x: 6, y: 3 },
	{ name: 'Iowa', abbr: 'IA', x: 5, y: 3 },
	{ name: 'Kansas', abbr: 'KS', x: 4, y: 5 },
	{ name: 'Kentucky', abbr: 'KY', x: 6, y: 4 },
	{ name: 'Louisiana', abbr: 'LA', x: 5, y: 6 },
	{ name: 'Maine', abbr: 'ME', x: 11, y: 0 },
	{ name: 'Maryland', abbr: 'MD', x: 9, y: 4 },
	{ name: 'Massachusetts', abbr: 'MA', x: 10, y: 2 },
	{ name: 'Michigan', abbr: 'MI', x: 7, y: 2 },
	{ name: 'Minnesota', abbr: 'MN', x: 5, y: 2 },
	{ name: 'Mississippi', abbr: 'MS', x: 6, y: 6 },
	{ name: 'Missouri', abbr: 'MO', x: 5, y: 4 },
	{ name: 'Montana', abbr: 'MT', x: 3, y: 2 },
	{ name: 'Nebraska', abbr: 'NE', x: 4, y: 4 },
	{ name: 'Nevada', abbr: 'NV', x: 2, y: 3 },
	{ name: 'New Hampshire', abbr: 'NH', x: 11, y: 1 },
	{ name: 'New Jersey', abbr: 'NJ', x: 9, y: 3 },
	{ name: 'New Mexico', abbr: 'NM', x: 3, y: 5 },
	{ name: 'New York', abbr: 'NY', x: 9, y: 2 },
	{ name: 'North Carolina', abbr: 'NC', x: 7, y: 5 },
	{ name: 'North Dakota', abbr: 'ND', x: 4, y: 2 },
	{ name: 'Ohio', abbr: 'OH', x: 7, y: 3 },
	{ name: 'Oklahoma', abbr: 'OK', x: 4, y: 6 },
	{ name: 'Oregon', abbr: 'OR', x: 1, y: 3 },
	{ name: 'Pennsylvania', abbr: 'PA', x: 8, y: 3 },
	{ name: 'Rhode Island', abbr: 'RI', x: 11, y: 3 },
	{ name: 'South Carolina', abbr: 'SC', x: 8, y: 5 },
	{ name: 'South Dakota', abbr: 'SD', x: 4, y: 3 },
	{ name: 'Tennessee', abbr: 'TN', x: 6, y: 5 },
	{ name: 'Texas', abbr: 'TX', x: 4, y: 7 },
	{ name: 'Utah', abbr: 'UT', x: 2, y: 4 },
	{ name: 'Vermont', abbr: 'VT', x: 10, y: 1 },
	{ name: 'Virginia', abbr: 'VA', x: 8, y: 4 },
	{ name: 'Washington', abbr: 'WA', x: 1, y: 2 },
	{ name: 'West Virginia', abbr: 'WV', x: 7, y: 4 },
	{ name: 'Wisconsin', abbr: 'WI', x: 6, y: 1 },
	{ name: 'Wyoming', abbr: 'WY', x: 3, y: 3 },
	{ name: 'District of Columbia', abbr: 'DC', x: 9, y: 5 }
];